motoman_mh5_mh50:
# MoveIt-specific simulation settings
  moveit_sim_hw_interface:
    joint_model_group: controllers_initial_group_
    joint_model_group_pose: controllers_initial_pose_
# Settings for ros_control control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - motoman_mh50_joint_1_s
      - motoman_mh50_joint_2_l
      - motoman_mh50_joint_3_u
      - motoman_mh50_joint_4_r
      - motoman_mh50_joint_5_b
      - motoman_mh50_joint_6_t
      - motoman_mh5_joint_s
      - motoman_mh5_joint_l
      - motoman_mh5_joint_u
      - motoman_mh5_joint_r
      - motoman_mh5_joint_b
      - motoman_mh5_joint_t
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  controller_list:
    - name: motoman_mh50_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - motoman_mh50_joint_1_s
        - motoman_mh50_joint_2_l
        - motoman_mh50_joint_3_u
        - motoman_mh50_joint_4_r
        - motoman_mh50_joint_5_b
        - motoman_mh50_joint_6_t
    - name: motoman_mh5_controller
      action_ns: follow_joint_trajectory
      default: True
      type: FollowJointTrajectory
      joints:
        - motoman_mh5_joint_s
        - motoman_mh5_joint_l
        - motoman_mh5_joint_u
        - motoman_mh5_joint_r
        - motoman_mh5_joint_b
        - motoman_mh5_joint_t