#controller_manager_ns: robot_controller_manager
controller_list:
  - name: ""
    action_ns: arm/joint_trajectory_controller/follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
