motoman_mh5_mh50:
  joint_names: [motoman_mh5_joint_s, motoman_mh5_joint_l, motoman_mh5_joint_u, motoman_mh5_joint_r, motoman_mh5_joint_b, motoman_mh5_joint_t]  
  max_command_silence: 0.5
  motoman_mh5_controller:
    type: position_controllers/JointTrajectoryController
    joints:
        - motoman_mh5_joint_s
        - motoman_mh5_joint_l
        - motoman_mh5_joint_u
        - motoman_mh5_joint_r
        - motoman_mh5_joint_b
        - motoman_mh5_joint_t
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        motoman_mh5_joint_s: {trajectory: 0.3, goal: 0.1}
        motoman_mh5_joint_l: {trajectory: 0.3, goal: 0.1}
        motoman_mh5_joint_u: {trajectory: 0.3, goal: 0.1}
        motoman_mh5_joint_r: {trajectory: 0.3, goal: 0.1}
        motoman_mh5_joint_b: {trajectory: 0.3, goal: 0.1}
        motoman_mh5_joint_t: {trajectory: 0.3, goal: 0.1}
    gains:
      motoman_mh5_joint_s: {p: 10000,  i: 50, d: 500, i_clamp_min: -100.0, i_clamp_max: 100.0}
      motoman_mh5_joint_l: {p: 10000,  i: 50, d: 500, i_clamp_min: -100.0, i_clamp_max: 100.0}
      motoman_mh5_joint_u: {p: 10000,  i: 50, d: 500, i_clamp_min: -100.0, i_clamp_max: 100.0}
      motoman_mh5_joint_r: {p: 10000,  i: 50, d: 500, i_clamp_min: -100.0, i_clamp_max: 100.0}
      motoman_mh5_joint_b: {p: 10000,  i: 50, d: 500, i_clamp_min: -100.0, i_clamp_max: 100.0}
      motoman_mh5_joint_t: {p: 10000,  i: 50, d: 500, i_clamp_min: -100.0, i_clamp_max: 100.0}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
    required_drive_mode: 7
